version: '3'
services:
  elasticsearch:
    image: blacktop/elasticsearch
  api:
    build:
      context: .
    image: malice/engine
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
  httpie:
    build:
      context: .
      dockerfile: Dockerfile.httpie
    links:
      - api
